name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shared-release:
    name: Release
    uses: hajle-silesia/.github/.github/workflows/shared-release.yaml@master
    secrets:
      token: ${{ secrets.PUSH_TOKEN }}
