name: Shared tests and static analysis

on:
  workflow_call:
    inputs:
      python-dependencies:
        description: Install Python dependencies?
        type: boolean
        required: false
        default: false

permissions:
  contents: read

jobs:
  shared-tests-and-statis-analysis:
    name: Shared tests and static analysis
    runs-on: ubuntu-latest
    container:
      image: hajlesilesia/toolbox:1.0.0

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit-zipapp
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install Python dependencies
        if: ${{ inputs.python-dependencies == true }}
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
      - name: Run tests and static analysis
        run: |
          pre-commit run --all-files --hook-stage manual
