# Source: https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions
# Source: https://github.com/semantic-release/semantic-release/blob/8fda7fd423d24e7b425fbee83790f49dd0478e2d/docs/recipes/ci-configurations/github-actions.md
name: Release

on:
  workflow_call:
    secrets:
      token:
        description: Token for pushing tags, publishing releases, commenting on issues and pull requests
        required: true

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Prevent semantic-release from making changes by "github-actions" user as it doesn't trigger other workflows
          # Source: https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions#pushing-package.json-changes-to-your-repository
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - name: Set up semantic-release
        run: |
          npx semantic-release@24.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
