name: Shared chart update

on:
  workflow_call:
    inputs:
      docker-hub-image-repository-name:
        description: Docker Hub image repository name
        type: string
        required: true
      image-tag:
        description: Image tag
        type: string
        required: true
    secrets:
      github-token:
        description: GitHub token
        required: true

permissions:
  contents: read

jobs:
  shared-chart-update:
    name: Shared chart update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}-config
      - uses: fjogeleit/yaml-update-action@v0.16.1
        with:
          commitChange: ${{ github.event_name != 'pull_request' }}
          repository: ${{ github.repository }}-config
          message: ${{ github.event.head_commit.message }}
          token: ${{ secrets.github-token }}
          changes: |
            {
              "charts/${{ github.event.repository.name }}/values.yaml": {
                "image.repository": "${{ inputs.docker-hub-image-repository-name }}",
                "image.tag": "${{ inputs.image-tag }}"
              },
              "charts/${{ github.event.repository.name }}/Chart.yaml": {
                "name": "${{ github.event.repository.name }}-config",
                "appVersion": "${{ inputs.image-tag }}"
              }
            }            
